### ISSUE TITLE
plugin.so doesn't work on Linux

### ISSUE THREAD

**Issue by g-elfling** [nysthi/nysthi#10]
I can't see the nysthi in the plugin menu list? I don't know why.. sorry I can't provide much info just that it doesn't work

**Comment by g-elfling** [comment]
Oh yeah! Found the error

`[warning] Failed to load library ./plugins/nysthi/plugin.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./plugins/nysthi/plugin.so)`

Dunno why. I vaguely remember this same problem from VCV Rack's first versions when I tried to use it....

**Comment by nysthi** [comment]
this time was compiled on fedora 26 directly!

**Comment by g-elfling** [comment]
What do you mean....I would really like to play with these modules :P Tried to google that error message but I can't figure it out

**Comment by nysthi** [comment]
are you running on ubuntu 16.04 or fedora 26 ?

**Comment by g-elfling** [comment]
Omg how did you know :D Ubuntu 16.04

**Comment by g-elfling** [comment]
`$ ldd --version
ldd (Ubuntu GLIBC 2.23-0ubuntu9) 2.23`

I have too old version maybe?

**Comment by nysthi** [comment]
you are the LINUX user, you are the expert... I'm OSX ... :D

**Comment by g-elfling** [comment]
lol:D

**Comment by gmschroeder** [comment]
Doesn't work for me, either. Anything I can do to help?

**Comment by nysthi** [comment]
do you have any information ? is it a crash ? a missing lib ? too old linux ?
I use FEDORA 26 and I have reports that is good for ubuntu 16.04

**Comment by g-elfling** [comment]
Ended up upgrading my system, so now NYSTHI plugins work:)!!! Been waiting for this moment a longtime, now just gotta learn how to use them lol :P Seems like this kinda Linux issues are common..my system just didn't have the new version that was needed. Followed this guide: https://askubuntu.com/a/164313

**Comment by nysthi** [comment]
BRAVO!

**Comment by g-elfling** [comment]
^__^

**Comment by gmschroeder** [comment]
Sorry, afk. I'll get you more details when I try to compile again.
Lubuntu 16.04, rolled my own vcv current.

Thanks for the quick response!

**Comment by gmschroeder** [comment]
`[warning] Failed to load library ./plugins/NYSTHI.zip/plugin.so: ./plugins/NYSTHI.zip/plugin.so: cannot open shared object file: Not a directory
`
`[warning] Failed to load library ./plugins/NYSTHI/plugin.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./plugins/NYSTHI/plugin.so)
`
That askubuntu link makes it sound like I can't get libstdc++.so.6 running without upgrading to a not-LTS version of Ubuntu.
What gives?

**Comment by nysthi** [comment]
sorry guys, but the LINUX users are you
and so YOU are the experts!  Not me: I'm an OSX user... ;)

**Comment by gmschroeder** [comment]
I'll figure out the fastest fix on current Ubuntu LTS without upgrading the
whole os and get back atcha.
Thanks!

**Comment by gmschroeder** [comment]
So it loads for me on ubuntu 16.04 now, and I didn't think I changed anything.
I still get the:
`[warning] Failed to load library ./plugins/NYSTHI.zip/plugin.so: ./plugins/NYSTHI.zip/plugin.so: cannot open shared`
But then later in the startup messages I get:
`[info] Loaded plugin ./plugins/NYSTHI/plugin.so`
I get similar messages for other plugins, so I'm leaving it for now.
Thanks!

**Comment by danballance** [comment]
Hi, I'm getting the same issue. Do you know what you did to get it working @gmschroeder ?

[warning] Failed to load library ./plugins/NYSTHI/plugin.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./plugins/NYSTHI/plugin.so)

I have a fully up to date Ubuntu 16.04 LTS. My guess is the plugin is requiring a version of glibc that the current LTS version of Ubuntu is unable to provide. So I'm curious that you seemed to get it to run? Breaking glibc can potentially break your whole operating system it's such a core dependency so I don' want to try any hacks outside of the package manager unless they are really well tested and understood.

BTW I think the warning you have is the start up process trying to run the zip file as well. Do you still have the zip file in your plugins folder alongside the extracted directory?

**Comment by gmschroeder** [comment]
I just started VCV up later and it worked. No idea what changed. I didn't
think I changed anything about glibc's configuration.
Removing the .zip files did it re: the warnings. Thanks!

**Comment by danballance** [comment]
Okay so following some research on StackOverflow this seems to be a technique that a number of people are recommending. I've just run the below on a fully up to date 16.04 and it works for me.

WARNING: DON'T RUN THIS ON AN IMPORTANT SYSTEM. YMMV. WORKED FOR ME BUT COULD BREAK FOR YOU.

> You need to upgrade libstdc++6 to latest version like this
> 
> sudo add-apt-repository ppa:ubuntu-toolchain-r/test
> sudo apt-get update
> sudo apt-get install gcc-4.9
> sudo apt-get upgrade libstdc++6
> After that you can check if you get GLIBCXX desired version like this:
> 
> strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX

https://stackoverflow.com/a/46613765/5237002

**Comment by davephillips** [comment]
Kent Williams posted a simple and elegant way to work around that verdammt symbols versioning done by some installations of GCC. I downloaded and unzipped the libstdc++.so.6 in http://cornwarning.com/xfer/libForRack.zip, dropped the lib into my $HOME/src/Rack-050/dep/lib directory, and voila, Antonio's superb modules now work with Rack on my ancient Fedora 23. Btw, it works because Rack's shell script declares its own LD_LIBRARY_PATH, which of course includes Rack/dep/lib. As far as I can tell, it's the least obtrusive/dangerous way to overcome the versioning problem, but I'd like to hear about anyone else's experience with this solution.

**Comment by antoniotuzzi** [comment]
BRAVO!

**Comment by cschol** [comment]
@nysthi Andrew and I were discussion this in the referenced [issue](https://github.com/VCVRack/community/issues/314) in the community repository.

Plugins should follow the same minimum version requirements as Rack does. This means plugins should be compiled with the same `libc` and `libstdc++` as Rack on the supported platforms, in this case Linux. Per Andrew, those versions are `libc v2.23` and `libstdc++ v5.4.0`. Those libraries are present on Ubuntu 16.04, for example.

**Compiling** on Ubuntu 16.04 and **running** on Fedora 26 will work, because both libraries are *forward-compatible*. **Compiling** on Fedora 26 and **running** on Ubuntu 16.04 (which is equivalent to the minimum supported Linux platform for Rack) does **not** work.

The workaround mentioned above relies on implementation defined behavior in Rack with the `LD_LIBRARY_PATH` and is not acceptable as a long-term solution. Only compiling the plugin with the minimum supported version is.

I have put together a Docker-based solution to help with this: [vcv-plugin-builder-linux](https://github.com/cschol/vcv-plugin-builder-linux). I would appreciate if you could try this solution out to help solve this issue. In this case, Docker provides a build environment based on Ubuntu 16.04 to compile the plugin source code. You should be able to run the script on Fedora 26 **after** installing Docker. Instructions are in the `README.md` of the [repository](https://github.com/cschol/vcv-plugin-builder-linux).

Please let me know if you have any issues or need help. Thank you for helping to provide this great plugin for all Rack users!

**Comment by cschol** [comment]
@antoniotuzzi Did you ever get a chance to try building your Linux plugin with the required supported version of libraries?

**Comment by antoniotuzzi** [comment]
Sorry I completely missed this part! I'll check your proposed solution as soon as I'll have time !

**Comment by nysthi** [comment]
@cschol I tried a couple of time using my mac (I have Docker, and is updated )
takes a HUGE time
and at the end the process is always close with error from compiler g++

Do you have more suggestions ?

(example:
> g++: internal compiler error: Killed (program cc1plus)
> Please submit a full bug report,
> with preprocessed source if appropriate.
> See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
> make: *** [build/src/DAHD.cpp.o] Error 4
> /opt/Rack/compile.mk:61: recipe for target 'build/src/DAHD.cpp.o' failed
> g++: internal compiler error: Killed (program cc1plus)
> Please submit a full bug report,
> with preprocessed source if appropriate.
> See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
> make: *** [build/src/MVerb.cpp.o] Error 4
> /opt/Rack/compile.mk:61: recipe for target 'build/src/MVerb.cpp.o' failed
> AntonioMBP15-2:vcv-plugin-builder-linux antoniotuzzi$
> AntonioMBP15-2:vcv-plugin-builder-linux antoniotuzzi$
)

**Comment by cschol** [comment]
@nysthi I don't know exactly what is going on there. Have you tried this on the Fedora machine you have? Maybe the build is running out of RAM on your Mac. I have seen `g++: internal compiler error` when the RAM was all used up. Also, it should not take a long time to compile either. Not much longer than outside of a Docker container anyway.

**Comment by davephillips** [comment]
@patman023 Not an issue for me, I'm still using the (very) unofficial solution of LD_LIBRARY_PATH=dep/lib

**Comment by cschol** [comment]
This is not an issue (anymore) **IF** you are using the NYSTHI plugins built by Andrew's official build system and distributed via the plugin manager. At the time of the issue was found, NYSTHI was only available from the GitHub releases page. It still might be an issue with the releases from GitHub, and if it is, it is related to the build environment used to create those release, see this [comment](https://github.com/nysthi/nysthi/issues/10#issuecomment-372524952).

**Comment by patman023** [comment]
Suggested close, can reopen or link to if more reports come in

**Comment by nysthi** [comment]
can't repro

**Comment by digitaltopo** [comment]
Just downloaded the plugin from the VCV plugin manager and get the same error other linux users are experiencing:

```
[0.025 warn src/plugin.cpp:90] Failed to load library /home/user/.Rack/plugins/NYSTHI/plugin.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/user/.Rack/plugins/NYSTHI/plugin.so)
```

System is Ubuntu 16.04
