### ISSUE TITLE
Clock Mult/Div 

### ISSUE THREAD

**Issue by NRG70** [nysthi/nysthi#147]
Hello friend!
Could you please add a rigger input for the RESET?
Also when the module is connected to CLOCK input, it should stop when there is no CLOCK coming in.
Otherwise it just keeps running/output messing the patch when the rest is stopped.

**Comment by nysthi** [comment]
what is a "rigger" ?

**Comment by nysthi** [comment]
done
in version 0 6 40
added a RESET input (via trig)

added a contextual menu to have a new mode
"NO CLOCK OUT, IF NO CLOCK IN IPUTS"

**Comment by nysthi** [comment]
add ACTIVE trig input + TAP: if not ACTIVE no CLOCKs are generated

**Comment by nysthi** [comment]
![screen shot 2019-02-16 at 12 26 11](https://user-images.githubusercontent.com/33201978/52899091-4fa58f00-31e6-11e9-976e-fc07e2825466.png)

**Comment by NRG70** [comment]
Thanks for the (t)rigger input :) !! 
But what i mean with CLOCK output stop, when NO clock signal =
No clock output from your module, when clock input IS connected, but clock input is LOW (not running, stopped).
I hope i am making any sense? :)

**Comment by nysthi** [comment]
that's impossible because this is a time computer and has no relation with current clock not running

a time computer uses 2 or more pulses to compute the current TEMPO/TIME

if you stop an incoming clock the time computer stays forever waiting for pulses

would be possible to add a check "IF PULSE is no incoming in 2 seconds (30 bpm)" but is not what you want: the computed clock will stop after at least 2 seconds

**Comment by nysthi** [comment]
(that't the reason I've add "ACTIVE" ON OFF: you can use the TRIG that stops the original CLOCK to STOP the computed clocks too)

**Comment by NRG70** [comment]
Ok understood, thanks! 
It's probably me trying to use it in a way that is not meant or designed for. 

Thanks again!

**Comment by NRG70** [comment]
not related question: " with time "computer" , do you mean: time calculator?

**Comment by nysthi** [comment]
yes
