### ISSUE TITLE
Nysthi Hot Tuna / TunaThor - High CPU usage

### ISSUE THREAD

**Issue by Krezie** [nysthi/nysthi#167]
Nysthi Hot Tuna and TunaThor seem to use a lot of CPU power.
On my Windows desktop system every added instance of Hot Tuna or TunaThor in VCV Rack seems to use about 15% CPU power.

See attached for screenshots and some information about my system and operating system.
[Nysthi HotTuna CPU Spikes.zip](https://github.com/nysthi/nysthi/files/3048675/Nysthi.HotTuna.CPU.Spikes.zip)

**Comment by nysthi** [comment]
thanks for the report

yes both (ad the Pitch2Voltage too) use a YIN autocorrelation method, and they use a separated thread to do it (that's the reason is invisible in VCV Rack meter)

and idling they are just going back and forth from the thread

if you insert a signal into the signal IN you'll see the processing power going up
