### ISSUE TITLE
falla con Simpliciter 

### ISSUE THREAD

**Issue by Jairodallos** [nysthi/nysthi#215]
Hola Leonardo
describo lo que ocurre:

- hago grabacion en simpliciter
- la quiero eliminar y doy click derecho (windows) para seleccionar DELETE
- se cierra VCV

me pasa después de varios procedimientos similares; no es en cada ocasión.

y por cierto una pregunta:
como se logra ver la onda en tiempo de grabación?, solo la puedo ver cuando desactivo el botón grabación

Gracias

**Comment by Jairodallos** [comment]
Veo que la función undo para el caso del render selection, no funciona.
si renderizo no hay como volver atrás.

**Comment by Jairodallos** [comment]
qué es yummer?
una especie de chorus?

**Comment by Jairodallos** [comment]
veo que el botón de UNI, no afecta de igual forma a la onda random así como lo hace con las demás ondas del boton WAVE; entiendo que el botón lo que hace es alternar entre desplazamiento frontal VS desplazamiento oscilante (frontal -reverso), cosa que no ocurre con la onda random.

**Comment by Jairodallos** [comment]
Felicitaciones por este módulo!
Muy teso vos.

**Comment by patman023** [comment]
Duuuuude...

https://github.com/patman023/nysthimanual/blob/master/changelog1.0.1_parsed.md#confusingsimpler

**Comment by Jairodallos** [comment]
Thanks
will go there

can you explain me the sync input operation?
the clock input is clear but not this



> Duuuuude...
> 
> https://github.com/patman023/nysthimanual/blob/master/changelog1.0.1_parsed.md#confusingsimpler
> 
> the core of both confusing simpler and simpliciter are the same.

**Comment by patman023** [comment]
https://github.com/patman023/nysthimanual/blob/master/changelog1.0.1_parsed.md#the-green-panel-the-modulation-panel

**Comment by nysthi** [comment]
1) can't reproduce the crash (on MAC, I use MAC)
please I need a consistent full sequence of operations to REPRO it

2)
there is NO UNDO (and don't know if I'll implement in the future)
PLEASE OPEN a separate ISSUE in ENGLISH with feature request
if I see some interest (like 10 people asking for the same feature, I'll do it... ;) )

3)
yummer it's a new effect, invented by me
it's a first version of what became the WHORMHOLIZER
it's not a chorus, but a a delay swarmer (yes I know, I invented it... :D )

4)
there is no WAVE to show in real time, because is just playing the inner stuff too
and with infinite recordinig will be impossible
with the new version the PRE-record time there will be some wave show

5)
regarding the UNI not affecting the random, please OPEN a separate ISSUE 
and I'll put in the list of things to check, please!

thank you for your efforts!

**Comment by Funk-Burasuta** [comment]
NYSTHI es de Antonio Tuzzi, no Leonardo Laguna Ruiz, quien diseña los modulos de la línea Vult.

**Comment by nysthi** [comment]
v1.0.4
---- bug: when modulating random was not respecting the "unipolar" "inverted" flags
