### ISSUE TITLE
Reset button/trig sets SQUONK to last stage and fires trig out 

### ISSUE THREAD

**Issue by ham-steamer** [nysthi/nysthi#23]
Instantiate a SQUONK.
Set active step to any stage other than last fully active stage.
Click or trig reset button.
Final active stage become active and fires very short trig (use Fundamental Scope or VCO->VCA to verify).

**Comment by nysthi** [comment]
It is the correct behaviour
because is set ready to start the sequence from first step (like a real analog sequencer, for example the ARP 1611)
for example you have 2 squonk and you want to start both at the first step whne the drum machine starts, you need to send a RESET to BOTH

the trig out is because is like selecting a stage
