### ISSUE TITLE
Hot Tuna: sharp and flat note read out

### ISSUE THREAD

**Issue by Eurikon** [nysthi/nysthi#263]
Hi Antonio!

Could it be possible to have a switch to switch between ♯ Sharp and ♭ Flat read out in the screen?

For example when switch is default (Sharp) , and note D# is played the screen shows D#.
But when the switch is set to Flat, and note "D#" is played the screen then would show E♭ .

I don't know if it exactly works that way, or if that is possible?
Thanks in advance!

**Comment by nysthi** [comment]
do you want both visible ?

(E♭/ D#)

or a contextual menu to change between 2 modes ?

anto

**Comment by Eurikon** [comment]
You may decide what fits best in your design. 
I will be happy with either :)

**Comment by nysthi** [comment]
extended string was not possible (too much space)
in version 1.0.10

-- HOTTUNA
---- add "USE BEMOLLE" (USE ♭) mode. When ON, bemolle (♭) are presented instead of Diesis (#)

-- GRAN TUNISMO
---- add "USE BEMOLLE" (USE ♭) mode. When ON, bemolle (♭) are presented instead of Diesis (#)


![Screen Shot 2019-12-25 at 16 01 07](https://user-images.githubusercontent.com/33201978/71447555-f2e10200-272f-11ea-92ff-657ddbc4edbf.png)

**Comment by Eurikon** [comment]
Thank you sir! Much love, happy holidays 🙏🏼
