### ISSUE TITLE
2.0.14 hangs Rack 2  2.0.4/5 browser completely

### ISSUE THREAD

**Issue by fractalgee** [nysthi/nysthi#384]
If I scroll though the modules in the browser in any sorting order it hangs about 20-30% down the way (according to scroll bar location and size). It hangs completely spinning until force quit (killed). If I move Nythi out of plugins browser scrolls fine all the way to end. None of the modules I use seem to cause any issues so not sure what else I can add. attached is a log example of a session that hung when Nysthi modules was in the plugin folder and the stack from the eventual kill after Rack went into a spin.

Rack 2 Pro 2.0.4/5
Nysthi 2.0.14
MacOS 11.6.2
Mac Mini M1 16GB

[log.txt](https://github.com/nysthi/nysthi/files/7820096/log.txt)

**Comment by nysthi** [comment]
try to set frame rate to 10 Hz and let me know

**Comment by nysthi** [comment]
ok you tested it

**Comment by nysthi** [comment]
it's something, I think, wrong in the "draw" mechanism for Rack
it the pages takes more time to draw that a single frame draw, the draw is skipped

I have no extra element drawing in the lib: example, my Phasor is not drawing the shapes
or the 7Seas not drawing the waves

but I have many modules with many elements (hundreds of knobs in case of musical box

I told Andrew that this algorithm would be dangerous for the future (because, debugging, in my slowness, I experimented before you the same problems)

it's happening now with my modules, but will happen with any combinations of complex modules!

**Comment by nysthi** [comment]
leaving open because I want to see RACK guys how they will avoid this bug

**Comment by fractalgee** [comment]
excellent, I already sent it back to VCV, as anything that goes into spinning cursor death is to me a bug in that app/process. Also, I agree that this approach seems a bit dangerous indeed, could explain some other issues with browser on other OSs as well (odd crashes, modules not drawn completely or not visible at all, etc)
