### ISSUE TITLE
Arm builds

### ISSUE THREAD

**Issue by trevormeier** [nysthi/nysthi#432]
Now that the API supports Arm builds, could you do an Arm build of the latest Nysthi? I’m collecting and testing Arm builds from other devs here: https://community.vcvrack.com/t/modules-with-arm-builds/18809/

**Comment by fractalgee** [comment]
adding my vote for Arm64 Mac builds (rack-toolchain and github actions as per @qno will build them if you so specify) so should be pretty easy hopefully. Otherwise I will be lost as all my patches include your Scala Quant minimally, so all would break if no arm64 build and Rosetta goes away (not too far off going by Apple's previous arch switch (PPC to Intel)).

Thanks for all the awesome modules, once again

**Comment by gabriel-roth** [comment]
+1. I have upgraded to the ARM build of VCV Rack and it's much faster but I miss using the wonderful NYSTHI modules!

**Comment by armandvedel** [comment]
+1
