### ISSUE TITLE
LOGAN20: Where is the logging-file? (RACK2 Pro)

### ISSUE THREAD

**Issue by scheichreisuli** [nysthi/nysthi#437]
Hi,

I tried to log some data with LOGAN20. But where is the file saved to?

In the short description of the module it is mentioned, that the default target is the plugin-folder. But there is no log-file, neither in the whole NYSTHI-plugin-folder, nor in the RACK-folder.

On May 24 2022 I played around with LOGAN20 (RACK2Pro) and there was a file saved, named

LOGAN20_20220524_104738_lRIGMC_LOGAN20_2ZHgyiBc.csv

It is also mentioned that the destination of the log-file can be set in the right-click-menu. Currently, I cannot find such a feature.

Please have a look at it.

Thank you for your attention.

**Comment by scheichreisuli** [comment]
Hi,

did you already had the chance to look at this issue? It would be very helpful to know where LOGAN20 stores its recordings.

Have a nice day.

**Comment by nysthi** [comment]
Hello!

Thank you for using it...

Are you using last version ?

https://github.com/nysthi/nysthi/releases/tag/v2.1.19 ?

in this version when you HIT RECORD a saving dialog is presented

or you can choose PRE record a name  and a sdestination to be used (and AUTOEMNUMERATED)

<img width="855" alt="Screenshot 2023-03-03 at 17 22 53" src="https://user-images.githubusercontent.com/33201978/222773186-093cc3cd-86fa-4191-9d1b-2c5444973879.png">

**Comment by scheichreisuli** [comment]
Thank you for your quick reply.

I use the version that is delivered and gets updated by vcv library, and that is 2.0.15. The screenshot shows the right-click-menu of tjat version.
![2023-03-04 13_18_16-VCV Rack Pro 2 2 3 logan20](https://user-images.githubusercontent.com/50453771/222900839-682ef7b8-9194-4dfc-b19c-afd7059ca43d.png)

I did not know that there is a newer version. How can I get the newer version? Will it be available using the vcv-library-update-functionality?

**Comment by scheichreisuli** [comment]
I found out how to update manually just by copying the NYSTHI-file to the plugins-folder of vcv rack.

The new version is available now - and has the destination-feature.

Thank you very much again for this wonderful collection.

**Comment by nysthi** [comment]
grazie mille!

**Comment by scheichreisuli** [comment]
Hi,

sorry to write again about LOAGN20, but there might be a bug in the module.

LOGAN20 seems to ignore the settings in the right-click-menu. I built a test-setup, recorded some sample-logs, wrote a readme-file and packed all in a ZIP. The ZIP is attached.

Have a nice day.
[logan20.zip](https://github.com/nysthi/nysthi/files/10899894/logan20.zip)

**Comment by nysthi** [comment]
instructions:


-- LOGAN
---- CSV logger with 6 values
---- the CSV is a Comma Separated Values file, that can be opened as spreadsheet
---- first line of the output are the titles: TICKS, MSECS, + VALUES titles
---- titles for single channels can be edited
---- if AUTOSAVE is ON, a file name "logan1_DATE_SOMENUMBERS.csv" will be automatically saved in the RACK directory
---- is AUTOSAVE is OFF a dialog will be presented
---- SAVING starts tapping the START button (or triggering it)
---- SAVING ends tapping the END button (or triggering it)
---- a contextual menu will let you choose the granularity of the saving
----- every sample, every 10 samples, every 100 samples, every 1000 samples, every 10000 samples
---- if LOG on TRIG input is occupied, saves will happen every time a PULSE is received


NOTICE: if you use TRIG the sample rate of saving will be ignored

YES ticks are n umber of samples since the START TRIG
YES the sampling is dependent on the current sample rate of your VCV

but if you use a TRIG system recording and a TRIG system PLAYING should be no problem

**Comment by scheichreisuli** [comment]
Thank you for clarification. I checked it out. Now I got it.

Have a nice day.
