### ISSUE TITLE
Quad does not save Wav names

### ISSUE THREAD

**Issue by odahan** [nysthi/nysthi#6]
Names of samples are not saved and then samples are not reloaded. (vcv 0.5)

**Comment by nysthi** [comment]
??
platform ?
Quad won't save any wave (there is no save as, is all automatic caching)

**Comment by blackearth2014** [comment]
Quadsimpler latest update crashes racks when trying to load old/new samples after saving a project and it doesn't load previous project samples.

**Comment by metaphorz** [comment]
I just saw this issue. See my just posted issue. Seems like we are having the same problems.

(1) The WAV files should, in theory, be stored along with the patch. Otherwise, everytime a musician loads this patch, they are forced to manually reload the WAV files (which does not make sense).

(2) The crashes when a WAV file is loaded, at least on a downloaded patch from someone else.

**Comment by nysthi** [comment]
audio sample will be never saved in the file
currently the system saves the autosave file every 15 secs
would be useless with PCM data FLAT to save,  let's say 80 MB every 15 secs

**Comment by metaphorz** [comment]
Easily solved by storing the names of the WAV files and not their contents. I’ve posted
separately on this in the other issue.

**Comment by nysthi** [comment]
the names are in

**Comment by nysthi** [comment]
already in

**Comment by metaphorz** [comment]
OK, when you save the names, do you save the entire filename path or just the name of the WAV file? I ask because I had issues at home and then going to work, where the WAV files were not loaded. Also, when you do the save, do you save in the user's cache or in the patch (if that is even possible)?

**Comment by nysthi** [comment]
I save them in the nysthi directory
try it
open a rack, put a simpler, load a file, close the patch
browse to your plugins/nysthi/cache/
you'll se a file named something.wav 
that's the one you have to move around 

but anyway, if there is crash for missing files, that's a bug !
but I don't have this crash with MAC !

**Comment by metaphorz** [comment]
I am gaining a better understanding of the sampler mechanism, and yes, I now see some WAV files underneath the nysthi/cache directory. But something is still off. I loaded the Dark Room patch just now. The samplers are in the patch, without any loaded WAVs. So, I first cleared the nysthi/cache by deleting everything already there. Then, I tried loading the topmost simpler with a new WAV. Rack crashed. Here is the report. Let me know if you can duplicate or whether I can do something to test.
Process:               Rack [46056]
Path:                  /Applications/Rack.app/Contents/MacOS/Rack
Identifier:            com.vcvrack.rack
Version:               ??? (???)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Rack [46056]
User ID:               501

Date/Time:             2017-11-30 11:55:43.894 -0600
OS Version:            Mac OS X 10.13.1 (17B48)
Report Version:        12
Anonymous UUID:        D6D40B3C-0FAD-6B61-AE53-2A01468BB84E

Sleep/Wake UUID:       3059DF44-C7B9-4856-93C1-7FD5B8404D3B

Time Awake Since Boot: 210000 seconds
Time Since Wake:       91000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGBUS)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x00007f971a93f000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Bus error: 10
Termination Reason:    Namespace SIGNAL, Code 0xa
Terminating Process:   exc handler [0]

VM Regions Near 0x7f971a93f000:
    MALLOC_TINY            00007f971a000000-00007f971a800000 [ 8192K] rw-/rwx SM=PRV  
--> MALLOC_SMALL           00007f971a800000-00007f971b000000 [ 8192K] rw-/rwx SM=COW  
    MALLOC_SMALL           00007f971b000000-00007f971e000000 [ 48.0M] rw-/rwx SM=PRV  

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   ???                           	0x00007f971a93f000 0 + 140286962692096
1   plugin.dylib                  	0x000000010ed2f6e4 complexSimpler::save_to_file(char const*) + 628
2   plugin.dylib                  	0x000000010ed2f422 complexSimpler::set_samples(double*, double*, long, double) + 258
3   plugin.dylib                  	0x000000010ed34c5e complexSimpler::load_file(char const*) + 606
4   plugin.dylib                  	0x000000010ed34805 NYOpenSaveWavItem::onAction(rack::EventAction&) + 341
5   com.vcvrack.rack              	0x000000010d72495b virtual thunk to rack::MenuItem::onDragDrop(rack::EventDragDrop&) + 59
6   com.vcvrack.rack              	0x000000010d6db01c rack::mouseButtonCallback(GLFWwindow*, int, int, int) + 364
7   com.vcvrack.rack              	0x000000010d6dc240 rack::guiRun() + 352
8   com.vcvrack.rack              	0x000000010d6e45aa main + 698
9   com.vcvrack.rack              	0x000000010d6c63e4 start + 52

Thread 1:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff7036de76 mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff7036d390 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff48ba7dd5 __CFRunLoopServiceMachPort + 341
3   com.apple.CoreFoundation      	0x00007fff48ba7127 __CFRunLoopRun + 1783
4   com.apple.CoreFoundation      	0x00007fff48ba6797 CFRunLoopRunSpecific + 487
5   com.apple.AppKit              	0x00007fff462f62d1 _NSEventThread + 184
6   libsystem_pthread.dylib       	0x00007fff704b16c1 _pthread_body + 340
7   libsystem_pthread.dylib       	0x00007fff704b156d _pthread_start + 377
8   libsystem_pthread.dylib       	0x00007fff704b0c5d thread_start + 13

Thread 2:
0   libsystem_kernel.dylib        	0x00007fff703771d2 __semwait_signal + 10
1   libsystem_c.dylib             	0x00007fff702f2754 nanosleep + 199
2   libc++.1.dylib                	0x00007fff6e2a6934 std::__1::this_thread::sleep_for(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > const&) + 73
3   com.vcvrack.rack              	0x000000010d70186b AudioInterface::step() + 107
4   com.vcvrack.rack              	0x000000010d6c6f4e rack::engineRun() + 366
5   com.vcvrack.rack              	0x000000010d6c7cfd void* std::__1::__thread_proxy<std::__1::tuple<void (*)()> >(void*) + 93
6   libsystem_pthread.dylib       	0x00007fff704b16c1 _pthread_body + 340
7   libsystem_pthread.dylib       	0x00007fff704b156d _pthread_start + 377
8   libsystem_pthread.dylib       	0x00007fff704b0c5d thread_start + 13

Thread 3:: com.apple.audio.IOThread.client
0   libsystem_kernel.dylib        	0x00007fff7036de76 mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff7036d390 mach_msg + 60
2   com.apple.audio.CoreAudio     	0x00007fff48612bea HALB_MachPort::SendMessageWithReply(unsigned int, unsigned int, unsigned int, unsigned int, mach_msg_header_t*, bool, unsigned int) + 124
3   com.apple.audio.CoreAudio     	0x00007fff48612b5d HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int) + 45
4   com.apple.audio.CoreAudio     	0x00007fff4860fbc9 HALC_ProxyIOContext::IOWorkLoop() + 977
5   com.apple.audio.CoreAudio     	0x00007fff4860f62c HALC_ProxyIOContext::IOThreadEntry(void*) + 128
6   com.apple.audio.CoreAudio     	0x00007fff4860f36e HALB_IOThread::Entry(void*) + 72
7   libsystem_pthread.dylib       	0x00007fff704b16c1 _pthread_body + 340
8   libsystem_pthread.dylib       	0x00007fff704b156d _pthread_start + 377
9   libsystem_pthread.dylib       	0x00007fff704b0c5d thread_start + 13

Thread 4:
0   libsystem_kernel.dylib        	0x00007fff703776da __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff704b106a _pthread_wqthread + 1035
2   libsystem_pthread.dylib       	0x00007fff704b0c4d start_wqthread + 13

Thread 5:
0   libsystem_kernel.dylib        	0x00007fff703776da __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff704b126f _pthread_wqthread + 1552
2   libsystem_pthread.dylib       	0x00007fff704b0c4d start_wqthread + 13

Thread 6:
0   libsystem_kernel.dylib        	0x00007fff703776da __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff704b106a _pthread_wqthread + 1035
2   libsystem_pthread.dylib       	0x00007fff704b0c4d start_wqthread + 13

Thread 7:
0   libsystem_pthread.dylib       	0x00007fff704b0c40 start_wqthread + 0
1   libxpc.dylib                  	0x00007fff704ea99e xpc_dictionary_get_audit_token + 75

Thread 8:: Dispatch queue: TBrowserViewDataSource
0   libsystem_kernel.dylib        	0x00007fff70376e7e __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff704b2662 _pthread_cond_wait + 732

**Comment by metaphorz** [comment]
Note that instead of opening Dark Room, which contains two pre-existing Simplers, I create a new Rack file (blank), I can create a simpler and load that WAV without any issue.

**Comment by nysthi** [comment]
good report! :D

**Comment by metaphorz** [comment]
I'll do some more experimenting. It seems that when I download another person's patch (who has not given me the nysthi/cache WAV files, I must delete their Simplers, create new ones, and re-patch. Otherwise, the crash occurs. Just try with this
[Dark-room.vcv.zip](https://github.com/nysthi/nysthi/files/1518976/Dark-room.vcv.zip)

**Comment by nysthi** [comment]
ok (in the meantime I was trying to reproduce locally, but I have no crash, I tried to remove files, remove the cache directory but never a crash)

now I'll open your file

**Comment by metaphorz** [comment]
yes, open it. The 2 simplers will be unloaded. Try loading.

**Comment by nysthi** [comment]
loaded, no crash
I guess you have permission problems for your mac
did you try to delete the "cache" directory
nysthi plugisn should recreate it

**Comment by metaphorz** [comment]
I have everything in DropBox. This makes it so that whatever computer I am on, I can just launch rack. I create a symbolic link from ~/Documents/Rack to Dropbox. So, all Rack files, including the plugins, your cache, etc are in the cloud. I am sysadmin on my machines. Here are the perms:

![screenshot 2017-11-30 12 28 53_preview](https://user-images.githubusercontent.com/3519631/33447887-24036b3e-d5ca-11e7-9996-ee20bb997048.png)

**Comment by metaphorz** [comment]
To add to this, recall that if I 1) delete a simpler, 2) create a new one in its place, 3) re-patch, and then 4) load the same WAV, everything works.

**Comment by metaphorz** [comment]
The last thing I can think of is maybe the versions are different with the simplers and that is causing the problem. Here is the original Dark Room patch where I cannot load new WAVs into it. The ZIP file I included above was my revised (new simplers built) version. 

https://patchstorage.com/dark-room/

**Comment by nysthi** [comment]
can't repro
