### ISSUE TITLE
Unimportant OP request

### ISSUE THREAD

**Issue by InductiveOne** [nysthi/nysthi#92]
I have to count jacks to remember what a couple things do (usually in the morning) and when I look at the right click legend it confuses me a bit every time. The legend is missing 3 of the controls. Also, under the CV pitch in jack, is it just passed out of the next jack? Lol, I also search for 4mix in the module browser a lot because that is what it is called on the panel. Both of these issues could be resolved by me learning.

![op the legend](https://user-images.githubusercontent.com/43386726/47942721-5aebdd80-dec9-11e8-8469-ec7bde96ba93.jpg)

**Comment by nysthi** [comment]
great ! I love the OP and I'll do an expanded VISUAL version
but with digital controls, I want the people to set by hand the exact ratios

sorry, I jumped some description because In my haed I was assuming they were clear ! :D

ok:

1)
yes the CV IN is copied immediatly in the CV OUT, because you want to pass it to the modulators
(my idea was to connect to the CV PITCH IN only the CARRIERs )

CVIO stands for  CV pith IN ad OUT 👍 

2)
yes is CV in to control the LIN FM VCA, so you can control it using any other CV controllers


I know about the 4mix name mismatch, let me see If I can correct it.. (at least add a dual name for searching)

**Comment by nysthi** [comment]
added missing part to the legenda

added missing names for mixers... :D

**Comment by nysthi** [comment]
in version 0 6 31

**Comment by nysthi** [comment]
released 0 6 31
